// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

import { API_BASE_PATH } from './api.types';
import type { WebhooksPostBody } from './api.types';

export async function getCrash(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/crash`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getHealth(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/health`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getInternalIssues(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/internal/issues`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getMetrics(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/metrics`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getReportSlow(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/report/slow`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function postWebhooks(body: WebhooksPostBody, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/webhooks`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}
