// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

export type VitekParams = Record<string, string>;
export type VitekQuery = Record<string, string | string[]>;


export type WebhooksPostBody = {
  type: string;
  payload?: unknown;
};

export interface CrashGetParams extends VitekParams {

}

export interface HealthGetParams extends VitekParams {

}

export interface InternalIssuesGetParams extends VitekParams {

}

export interface MetricsGetParams extends VitekParams {

}

export interface ReportSlowGetParams extends VitekParams {

}

export interface WebhooksPostParams extends VitekParams {

}

export type VitekRoute =
  | {
      pattern: 'crash';
      method: 'get';
      params: CrashGetParams;
    }
  | {
      pattern: 'health';
      method: 'get';
      params: HealthGetParams;
    }
  | {
      pattern: 'internal/issues';
      method: 'get';
      params: InternalIssuesGetParams;
    }
  | {
      pattern: 'metrics';
      method: 'get';
      params: MetricsGetParams;
    }
  | {
      pattern: 'report/slow';
      method: 'get';
      params: ReportSlowGetParams;
    }
  | {
      pattern: 'webhooks';
      method: 'post';
      params: WebhooksPostParams;
    };

export const API_BASE_PATH = '/api' as const;
