// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

export type VitekParams = Record<string, string>;
export type VitekQuery = Record<string, string | string[]>;


export type FilesPostBody = {
  filename: string;
  content: string;
  mimeType: string;
  size: number;
};

export type NotificationsPostBody = {
  title: string;
  message: string;
  userId: number;
};

export type PostsIdCommentsPostBody = {
  text: string;
  authorId: number;
  parentId?: number;
};

export type PostsIdPutBody = {
  title: string;
  content: string;
  authorId: number;
  tags?: string[];
};

export type PostsPostBody = {
  title: string;
  content: string;
  authorId: number;
  tags?: string[];
};

export type SettingsPutBody = {
  theme: 'light' | 'dark' | 'auto';
  language: string;
  notifications: {
    email: boolean;
    push: boolean;
  };
};

export type UsersIdPostsPostBody = {
  title: string;
  content: string;
  tags?: string[];
};

export type UsersIdSettingsPatchBody = {
  theme?: 'light' | 'dark' | 'auto';
  language?: string;
  notifications?: {
    email?: boolean;
    push?: boolean;
  };
};

export type UsersIdPatchBody = {
  name?: string;
  email?: string;
  age?: number;
};

export type UsersIdPostBody = {
  name: string;
  email: string;
  age?: number;
};

export type UsersIdPutBody = {
  name: string;
  email: string;
  age?: number;
};

export type AnalyticsGetQuery = {
  startDate: string;
  endDate: string;
  metric: 'views' | 'clicks' | 'conversions';
  groupBy?: 'day' | 'week' | 'month';
};

export type CorsOptionsQuery = {
  origin?: string;
};

export type FilesIdOptionsQuery = {
  origin?: string;
  method?: string;
};

export type NotificationsPostQuery = {
  priority?: 'low' | 'medium' | 'high';
  sendEmail?: boolean;
};

export type PostsIdCommentsGetQuery = {
  limit?: number;
  offset?: number;
  order?: 'asc' | 'desc';
  includeDeleted?: boolean;
};

export type PostsIdCommentsPostQuery = {
  notify?: boolean;
  sendEmail?: boolean;
};

export type SearchGetQuery = {
  q: string;
  limit?: number;
  offset?: number;
  sort?: 'asc' | 'desc';
};

export type SettingsPutQuery = {
  applyToAll?: boolean;
  overwrite?: boolean;
};

export type UsersIdPostsGetQuery = {
  limit?: number;
  offset?: number;
  status?: 'draft' | 'published' | 'archived';
  sortBy?: 'createdAt' | 'updatedAt' | 'title';
};

export type UsersIdPostsPostQuery = {
  publish?: boolean;
  notifyFollowers?: boolean;
};

export type UsersIdSettingsPatchQuery = {
  notify?: boolean;
  logChange?: boolean;
};

export interface AnalyticsGetParams extends VitekParams {
  // No dynamic params
}

export interface CommentsPostIdCommentIdDeleteParams extends VitekParams {
  postId: string;
  commentId: string;
}

export interface CommentsPostIdCommentIdGetParams extends VitekParams {
  postId: string;
  commentId: string;
}

export interface CorsOptionsParams extends VitekParams {
  // No dynamic params
}

export interface FilesIdHeadParams extends VitekParams {
  id: string;
}

export interface FilesIdOptionsParams extends VitekParams {
  id: string;
}

export interface FilesPostParams extends VitekParams {
  // No dynamic params
}

export interface HealthGetParams extends VitekParams {
  // No dynamic params
}

export interface NotificationsPostParams extends VitekParams {
  // No dynamic params
}

export interface PostsIdsGetParams extends VitekParams {
  ids: string;
}

export interface PostsIdCommentsGetParams extends VitekParams {
  id: string;
}

export interface PostsIdCommentsPostParams extends VitekParams {
  id: string;
}

export interface PostsIdDeleteParams extends VitekParams {
  id: string;
}

export interface PostsIdGetParams extends VitekParams {
  id: string;
}

export interface PostsIdPutParams extends VitekParams {
  id: string;
}

export interface PostsGetParams extends VitekParams {
  // No dynamic params
}

export interface PostsPostParams extends VitekParams {
  // No dynamic params
}

export interface SearchGetParams extends VitekParams {
  // No dynamic params
}

export interface SettingsPutParams extends VitekParams {
  // No dynamic params
}

export interface UsersIdPostsGetParams extends VitekParams {
  id: string;
}

export interface UsersIdPostsPostParams extends VitekParams {
  id: string;
}

export interface UsersIdSettingsPatchParams extends VitekParams {
  id: string;
}

export interface UsersIdDeleteParams extends VitekParams {
  id: string;
}

export interface UsersIdGetParams extends VitekParams {
  id: string;
}

export interface UsersIdPatchParams extends VitekParams {
  id: string;
}

export interface UsersIdPostParams extends VitekParams {
  id: string;
}

export interface UsersIdPutParams extends VitekParams {
  id: string;
}

export interface VersionGetParams extends VitekParams {
  // No dynamic params
}

export type VitekRoute =
  | {
      pattern: 'analytics';
      method: 'get';
      params: AnalyticsGetParams;
    }
  | {
      pattern: 'comments/:postId/:commentId';
      method: 'delete';
      params: CommentsPostIdCommentIdDeleteParams;
    }
  | {
      pattern: 'comments/:postId/:commentId';
      method: 'get';
      params: CommentsPostIdCommentIdGetParams;
    }
  | {
      pattern: 'cors';
      method: 'options';
      params: CorsOptionsParams;
    }
  | {
      pattern: 'files/:id';
      method: 'head';
      params: FilesIdHeadParams;
    }
  | {
      pattern: 'files/:id';
      method: 'options';
      params: FilesIdOptionsParams;
    }
  | {
      pattern: 'files/index';
      method: 'post';
      params: FilesPostParams;
    }
  | {
      pattern: 'health';
      method: 'get';
      params: HealthGetParams;
    }
  | {
      pattern: 'notifications/index';
      method: 'post';
      params: NotificationsPostParams;
    }
  | {
      pattern: 'posts/*ids';
      method: 'get';
      params: PostsIdsGetParams;
    }
  | {
      pattern: 'posts/:id/comments';
      method: 'get';
      params: PostsIdCommentsGetParams;
    }
  | {
      pattern: 'posts/:id/comments';
      method: 'post';
      params: PostsIdCommentsPostParams;
    }
  | {
      pattern: 'posts/:id';
      method: 'delete';
      params: PostsIdDeleteParams;
    }
  | {
      pattern: 'posts/:id';
      method: 'get';
      params: PostsIdGetParams;
    }
  | {
      pattern: 'posts/:id';
      method: 'put';
      params: PostsIdPutParams;
    }
  | {
      pattern: 'posts/index';
      method: 'get';
      params: PostsGetParams;
    }
  | {
      pattern: 'posts/index';
      method: 'post';
      params: PostsPostParams;
    }
  | {
      pattern: 'search';
      method: 'get';
      params: SearchGetParams;
    }
  | {
      pattern: 'settings';
      method: 'put';
      params: SettingsPutParams;
    }
  | {
      pattern: 'users/:id/posts';
      method: 'get';
      params: UsersIdPostsGetParams;
    }
  | {
      pattern: 'users/:id/posts';
      method: 'post';
      params: UsersIdPostsPostParams;
    }
  | {
      pattern: 'users/:id/settings';
      method: 'patch';
      params: UsersIdSettingsPatchParams;
    }
  | {
      pattern: 'users/:id';
      method: 'delete';
      params: UsersIdDeleteParams;
    }
  | {
      pattern: 'users/:id';
      method: 'get';
      params: UsersIdGetParams;
    }
  | {
      pattern: 'users/:id';
      method: 'patch';
      params: UsersIdPatchParams;
    }
  | {
      pattern: 'users/:id';
      method: 'post';
      params: UsersIdPostParams;
    }
  | {
      pattern: 'users/:id';
      method: 'put';
      params: UsersIdPutParams;
    }
  | {
      pattern: 'version';
      method: 'get';
      params: VersionGetParams;
    };

export const API_BASE_PATH = '/api' as const;
