// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

import { API_BASE_PATH } from './api.types.js';
import type { CommentsPostIdCommentIdDeleteParams, CommentsPostIdCommentIdGetParams, FilesIdHeadParams, FilesIdOptionsParams, PostsIdsGetParams, PostsIdCommentsGetParams, PostsIdCommentsPostParams, PostsIdDeleteParams, PostsIdGetParams, PostsIdPutParams, UsersIdPostsGetParams, UsersIdPostsPostParams, UsersIdSettingsPatchParams, UsersIdDeleteParams, UsersIdGetParams, UsersIdPatchParams, UsersIdPostParams, UsersIdPutParams, FilesPostBody, NotificationsPostBody, PostsIdCommentsPostBody, PostsIdPutBody, PostsPostBody, SettingsPutBody, UsersIdPostsPostBody, UsersIdSettingsPatchBody, UsersIdPatchBody, UsersIdPostBody, UsersIdPutBody, AnalyticsGetQuery, CorsOptionsQuery, FilesIdOptionsQuery, NotificationsPostQuery, PostsIdCommentsGetQuery, PostsIdCommentsPostQuery, SearchGetQuery, SettingsPutQuery, UsersIdPostsGetQuery, UsersIdPostsPostQuery, UsersIdSettingsPatchQuery } from './api.types.js';

export async function getAnalytics(query: AnalyticsGetQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/analytics`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function deleteCommentsPostIdCommentId(params: CommentsPostIdCommentIdDeleteParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/comments/${params.postId}/${params.commentId}`, {
    method: 'DELETE',
    ...options,
  }).then(res => res.json());
}

export async function getCommentsPostIdCommentId(params: CommentsPostIdCommentIdGetParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/comments/${params.postId}/${params.commentId}`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function optionsCors(query: CorsOptionsQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/cors`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'OPTIONS',
    ...options,
  }).then(res => res.json());
}

export async function headFilesId(params: FilesIdHeadParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/files/${params.id}`, {
    method: 'HEAD',
    ...options,
  }).then(res => res.json());
}

export async function optionsFilesId(params: FilesIdOptionsParams, query: FilesIdOptionsQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/files/${params.id}`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'OPTIONS',
    ...options,
  }).then(res => res.json());
}

export async function postFiles(body: FilesPostBody, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/files`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function getHealth(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/health`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function postNotifications(body: NotificationsPostBody, query: NotificationsPostQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/notifications`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function getPostsIds(params: PostsIdsGetParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/posts/${params.ids}`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getPostsIdComments(params: PostsIdCommentsGetParams, query: PostsIdCommentsGetQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/posts/${params.id}/comments`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function postPostsIdComments(params: PostsIdCommentsPostParams, body: PostsIdCommentsPostBody, query: PostsIdCommentsPostQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/posts/${params.id}/comments`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function deletePostsId(params: PostsIdDeleteParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/posts/${params.id}`, {
    method: 'DELETE',
    ...options,
  }).then(res => res.json());
}

export async function getPostsId(params: PostsIdGetParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/posts/${params.id}`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function putPostsId(params: PostsIdPutParams, body: PostsIdPutBody, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/posts/${params.id}`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function getPosts(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/posts`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function postPosts(body: PostsPostBody, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/posts`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function getSearch(query: SearchGetQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/search`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function putSettings(body: SettingsPutBody, query: SettingsPutQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/settings`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function getUsersIdPosts(params: UsersIdPostsGetParams, query: UsersIdPostsGetQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/users/${params.id}/posts`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function postUsersIdPosts(params: UsersIdPostsPostParams, body: UsersIdPostsPostBody, query: UsersIdPostsPostQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/users/${params.id}/posts`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function patchUsersIdSettings(params: UsersIdSettingsPatchParams, body: UsersIdSettingsPatchBody, query: UsersIdSettingsPatchQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/users/${params.id}/settings`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function deleteUsersId(params: UsersIdDeleteParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/users/${params.id}`, {
    method: 'DELETE',
    ...options,
  }).then(res => res.json());
}

export async function getUsersId(params: UsersIdGetParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/users/${params.id}`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function patchUsersId(params: UsersIdPatchParams, body: UsersIdPatchBody, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/users/${params.id}`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function postUsersId(params: UsersIdPostParams, body: UsersIdPostBody, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/users/${params.id}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function putUsersId(params: UsersIdPutParams, body: UsersIdPutBody, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/users/${params.id}`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function getVersion(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/version`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}
