/**
 * TypeScript type generation for sockets
 * Core logic - no Vite dependencies
 */

import * as fs from 'fs';
import * as path from 'path';
import type { SocketSchema } from './socket-schema.js';
import { capitalize } from '../../shared/utils.js';

/**
 * Generates the content of the generated socket types file
 */
export function generateSocketTypesContent(
  sockets: SocketSchema[],
  socketBasePath: string
): string {
  const imports = `// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your socket files

import type { WebSocket } from 'ws';
import type { IncomingMessage } from 'http';

export const SOCKET_BASE_PATH = '${socketBasePath}' as const;

export interface VitekSocketContext {
  socket: WebSocket;
  req: IncomingMessage;
  params: Record<string, string>;
  path: string;
}

export type VitekSocket = WebSocket;
`;

  if (sockets.length === 0) {
    return `${imports}

export type VitekSocketRoute = never;
`;
  }

  const typeNameMap = generateUniqueSocketParamNames(sockets);

  const paramTypes = sockets
    .filter((s) => s.params.length > 0)
    .map((socket) => {
      const typeName = typeNameMap.get(socket.pattern)!;
      const paramsDef = socket.params.map((p) => `  ${p}: string;`).join('\n');
      return `export interface ${typeName} {
${paramsDef}
}`;
    })
    .filter((type, index, arr) => {
      const typeName = type.match(/^export interface (\w+)/)?.[1];
      return (
        typeName &&
        arr.findIndex((t) => t.match(/^export interface (\w+)/)?.[1] === typeName) === index
      );
    })
    .join('\n\n');

  const routeDefinitions = sockets.map((socket) => {
    const typeName =
      socket.params.length > 0 ? typeNameMap.get(socket.pattern)! : 'Record<string, never>';
    return `  | {
      pattern: '${socket.pattern}';
      params: ${typeName};
    }`;
  });

  const unionType = `export type VitekSocketRoute =\n${routeDefinitions.join('\n')};`;

  return `${imports}
${paramTypes ? paramTypes + '\n\n' : ''}
${unionType}
`;
}

/**
 * Returns unique param type names for sockets (used by services generator)
 */
export function getSocketParamTypeNames(sockets: SocketSchema[]): Map<string, string> {
  return generateUniqueSocketParamNames(sockets);
}

function generateUniqueSocketParamNames(sockets: SocketSchema[]): Map<string, string> {
  const nameMap = new Map<string, string>();
  const allUsedNames = new Set<string>();
  const groups = new Map<string, SocketSchema[]>();

  sockets.forEach((socket) => {
    const baseName = generateSocketTypeNameBase(socket);
    if (!groups.has(baseName)) {
      groups.set(baseName, []);
    }
    groups.get(baseName)!.push(socket);
  });

  sockets.forEach((socket) => {
    const baseName = generateSocketTypeNameBase(socket);
    const conflicting = groups.get(baseName)!;
    let uniqueName: string;
    if (conflicting.length === 1) {
      uniqueName = baseName;
    } else {
      uniqueName = generateUniqueSocketTypeName(socket, baseName, conflicting, allUsedNames);
    }
    nameMap.set(socket.pattern, uniqueName);
    allUsedNames.add(uniqueName);
  });

  return nameMap;
}

function generateSocketTypeNameBase(socket: SocketSchema): string {
  const parts = socket.pattern
    .split('/')
    .filter(Boolean)
    .map((part) => {
      const clean = part.replace(/^[:*]/, '');
      return clean === 'index' ? '' : capitalize(clean);
    });
  return parts.filter(Boolean).join('') + 'SocketParams';
}

function generateUniqueSocketTypeName(
  socket: SocketSchema,
  baseName: string,
  conflicting: SocketSchema[],
  allUsedNames: Set<string>
): string {
  const patternParts = socket.pattern.split('/').filter(Boolean);
  const allParts = patternParts
    .filter((p) => p !== 'index')
    .map((p) => capitalize(p.replace(/^[:*]/, '')));

  if (allParts.length > 0) {
    const candidate = allParts.join('') + 'SocketParams';
    if (!allUsedNames.has(candidate)) {
      return candidate;
    }
  }

  let counter = 1;
  let uniqueName = `${baseName}${counter}`;
  while (allUsedNames.has(uniqueName)) {
    counter++;
    uniqueName = `${baseName}${counter}`;
  }
  return uniqueName;
}

/**
 * Writes the generated socket types file
 */
export async function generateSocketTypesFile(
  outputPath: string,
  sockets: SocketSchema[],
  socketBasePath: string
): Promise<void> {
  const content = generateSocketTypesContent(sockets, socketBasePath);
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(outputPath, content, 'utf-8');
}
