/**
 * Client service generation for sockets
 * Core logic - no Vite dependencies
 */

import * as fs from 'fs';
import * as path from 'path';
import type { SocketSchema } from './socket-schema.js';
import { getSocketParamTypeNames } from './generate-socket-types.js';
import { capitalize } from '../../shared/utils.js';

/**
 * Generates the content of the generated socket services file
 */
export function generateSocketServicesContent(
  sockets: SocketSchema[],
  socketBasePath: string,
  isTypeScript: boolean = true
): string {
  const imports = `// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your socket files

${isTypeScript ? "import { SOCKET_BASE_PATH } from './socket.types.js';\n" : `const SOCKET_BASE_PATH = '${socketBasePath}';\n`}
`;

  const functionNameMap = generateUniqueSocketFunctionNames(sockets);
  const typeNameMap = isTypeScript ? getSocketParamTypeNames(sockets) : null;

  const functions = sockets.map((socket) => {
    const functionName = functionNameMap.get(socket.pattern)!;
    const paramsType = socket.params.length > 0 && typeNameMap ? typeNameMap.get(socket.pattern) : null;
    const wsPath = buildSocketPath(socket.pattern, socket.params);

    let params: string;
    if (socket.params.length === 0) {
      params = isTypeScript ? '(): WebSocket' : '()';
    } else {
      params = isTypeScript
        ? `(params: ${paramsType!}): WebSocket`
        : `(params)`;
    }

    const urlCode = `  const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  const url = new URL(\`\${protocol}//\${window.location.host}\${SOCKET_BASE_PATH}${wsPath}\`);
  return new WebSocket(url.toString());`;

    return `export function ${functionName}${params} {
${urlCode}
}`;
  });

  return `${imports}${functions.join('\n\n')}
`;
}

function generateUniqueSocketFunctionNames(sockets: SocketSchema[]): Map<string, string> {
  const nameMap = new Map<string, string>();
  const groups = new Map<string, SocketSchema[]>();

  sockets.forEach((socket) => {
    const base = generateSocketFunctionNameBase(socket);
    if (!groups.has(base)) groups.set(base, []);
    groups.get(base)!.push(socket);
  });

  sockets.forEach((socket) => {
    const base = generateSocketFunctionNameBase(socket);
    const conflicting = groups.get(base)!;
    const unique =
      conflicting.length === 1 ? base : generateUniqueSocketFunctionName(socket, base, conflicting, nameMap);
    nameMap.set(socket.pattern, unique);
  });

  return nameMap;
}

function generateSocketFunctionNameBase(socket: SocketSchema): string {
  if (socket.pattern === '') {
    return 'connect';
  }
  const parts = socket.pattern
    .split('/')
    .filter(Boolean)
    .filter((p) => p !== 'index')
    .map((p) => capitalize(p.replace(/^[:*]/, '')));
  return 'connect' + parts.join('');
}

function generateUniqueSocketFunctionName(
  socket: SocketSchema,
  baseName: string,
  conflicting: SocketSchema[],
  existing: Map<string, string>
): string {
  const used = new Set(existing.values());
  let i = 1;
  while (used.has(baseName + i)) i++;
  return baseName + i;
}

/**
 * Builds the path template for the WebSocket URL (for use in generated template literal)
 * Example: '' -> '/'
 * Example: 'chat' -> '/chat'
 * Example: 'rooms/:id' -> '/rooms/${params.id}' (literal ${params.id} in output)
 */
function buildSocketPath(pattern: string, params: string[]): string {
  if (pattern === '') {
    return '/';
  }
  let p = '/' + pattern.replace(/\/index$/, '').replace(/^index\//, '');
  if (p === '/index') p = '/';
  params.forEach((param) => {
    const placeholder = '${params.' + param + '}';
    p = p.replace(':' + param, placeholder).replace('*' + param, placeholder);
  });
  return p;
}

/**
 * Writes the generated socket services file
 */
export async function generateSocketServicesFile(
  outputPath: string,
  sockets: SocketSchema[],
  socketBasePath: string,
  isTypeScript: boolean = true
): Promise<void> {
  const content = generateSocketServicesContent(sockets, socketBasePath, isTypeScript);
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(outputPath, content, 'utf-8');
}
