import { describe, it, expect } from 'vitest';
import { generateSocketServicesContent } from './generate-socket-services.js';
import type { SocketSchema } from './socket-schema.js';

const SOCKET_BASE = '/api/ws';

function socket(pattern: string, params: string[] = [], file?: string): SocketSchema {
  return {
    pattern,
    params,
    file: file ?? `/api/${pattern.replace(/:/g, '[id]')}.socket.ts`,
  };
}

function getExportedFunctionNames(content: string): string[] {
  const matches = content.matchAll(/export function (\w+)/g);
  return [...matches].map((m) => m[1]);
}

function countOccurrences(str: string, name: string): number {
  const re = new RegExp(`export function ${name}\\b`, 'g');
  return (str.match(re) || []).length;
}

describe('generateSocketServicesContent', () => {
  it('returns valid content for empty sockets', () => {
    const content = generateSocketServicesContent([], SOCKET_BASE, true);
    expect(content).toContain('Auto-generated by Vitek');
    expect(content).toContain('SOCKET_BASE_PATH');
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(0);
  });

  it('generates exactly one function per unique socket pattern', () => {
    const sockets = [socket('chat'), socket('rooms/:id', ['id'])];
    const content = generateSocketServicesContent(sockets, SOCKET_BASE, true);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(2);
    expect(new Set(names).size).toBe(2);
  });

  it('deduplicates sockets: duplicate pattern produces single export', () => {
    const sockets = [
      socket('chat', [], '/api/chat.socket.ts'),
      socket('chat', [], '/other/chat.socket.ts'),
    ];
    const content = generateSocketServicesContent(sockets, SOCKET_BASE, true);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(1);
    expect(countOccurrences(content, names[0])).toBe(1);
  });

  it('deduplicates sockets: same pattern three times produces one function', () => {
    const sockets = [
      socket('notifications'),
      socket('notifications'),
      socket('notifications'),
    ];
    const content = generateSocketServicesContent(sockets, SOCKET_BASE, true);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(1);
    expect(countOccurrences(content, names[0])).toBe(1);
  });

  it('no duplicate export names: every exported function appears exactly once', () => {
    const sockets = [
      socket('chat'),
      socket('chat'),
      socket('presence'),
      socket('presence'),
      socket('rooms/:id', ['id']),
      socket('rooms/:id', ['id']),
    ];
    const content = generateSocketServicesContent(sockets, SOCKET_BASE, true);
    const names = getExportedFunctionNames(content);
    names.forEach((name) => {
      expect(countOccurrences(content, name)).toBe(1);
    });
    expect(names).toHaveLength(3);
  });

  it('JavaScript output: also deduplicates and has no duplicate exports', () => {
    const sockets = [
      socket('chat'),
      socket('chat'),
    ];
    const content = generateSocketServicesContent(sockets, SOCKET_BASE, false);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(1);
    expect(countOccurrences(content, names[0])).toBe(1);
  });

  it('regression: generated file has no duplicate export declarations', () => {
    const sockets = [
      socket('notifications'),
      socket('notifications'),
      socket('presence'),
      socket('presence'),
    ];
    const content = generateSocketServicesContent(sockets, SOCKET_BASE, true);
    const names = getExportedFunctionNames(content);
    const byName = names.reduce<Record<string, number>>((acc, n) => {
      acc[n] = (acc[n] ?? 0) + 1;
      return acc;
    }, {});
    Object.entries(byName).forEach(([, count]) => {
      expect(count).toBe(1);
    });
  });
});
