import { describe, it, expect } from 'vitest';
import { generateTypesContent, generateServicesContent } from './generate.js';
import type { RouteSchema } from './schema.js';

const API_BASE = '/api';

function route(
  pattern: string,
  method: string,
  params: string[] = [],
  overrides: Partial<RouteSchema> = {}
): RouteSchema {
  return {
    pattern,
    method,
    params,
    file: `/api/${pattern.replace(/:/g, '[id]')}.${method}.ts`,
    ...overrides,
  };
}

function getExportedFunctionNames(servicesContent: string): string[] {
  const matches = servicesContent.matchAll(/export async function (\w+)/g);
  return [...matches].map((m) => m[1]);
}

function getExportedParamInterfaceNames(typesContent: string): string[] {
  const matches = typesContent.matchAll(/export interface (\w+) extends VitekParams/g);
  return [...matches].map((m) => m[1]);
}

function countOccurrences(str: string, name: string): number {
  const re = new RegExp(`export async function ${name}\\b`, 'g');
  return (str.match(re) || []).length;
}

describe('generateTypesContent', () => {
  it('returns valid content for empty routes', () => {
    const content = generateTypesContent([], API_BASE);
    expect(content).toContain('VitekParams');
    expect(content).toContain('VitekRoute');
    expect(content).toContain('never');
    expect(content).toContain(`API_BASE_PATH = '${API_BASE}'`);
  });

  it('generates one param interface per unique route', () => {
    const routes = [
      route('health', 'get'),
      route('users/:id', 'get', ['id']),
    ];
    const content = generateTypesContent(routes, API_BASE);
    const names = getExportedParamInterfaceNames(content);
    expect(names.length).toBe(2);
    expect(new Set(names).size).toBe(2);
  });

  it('deduplicates routes: duplicate routeKey produces single param interface', () => {
    const routes = [
      route('flows/:id/run', 'post', ['id'], { file: '/api/flows/[id]/run.post.ts' }),
      route('flows/:id/run', 'post', ['id'], { file: '/api/flows/[id]/run.post.ts' }),
    ];
    const content = generateTypesContent(routes, API_BASE);
    const names = getExportedParamInterfaceNames(content);
    expect(names).toHaveLength(1);
  });

  it('deduplicates routes: same endpoint three times produces one interface', () => {
    const routes = [
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'get', ['id']),
    ];
    const content = generateTypesContent(routes, API_BASE);
    const names = getExportedParamInterfaceNames(content);
    expect(names).toHaveLength(1);
  });

  it('keeps first occurrence when deduplicating (pattern in union)', () => {
    const routes = [
      route('squads/:id', 'get', ['id']),
      route('squads/:id', 'get', ['id']),
    ];
    const content = generateTypesContent(routes, API_BASE);
    expect(content).toContain("pattern: 'squads/:id'");
    const count = (content.match(/pattern: 'squads\/:id'/g) || []).length;
    expect(count).toBe(1);
  });

  it('does not duplicate body type when routes are duplicated', () => {
    const routes = [
      route('users', 'post', [], { bodyType: '{ name: string }' }),
      route('users', 'post', [], { bodyType: '{ name: string }' }),
    ];
    const content = generateTypesContent(routes, API_BASE);
    const paramNames = getExportedParamInterfaceNames(content);
    expect(paramNames.length).toBe(1);
    const bodyTypeOccurrences = (content.match(/name: string/g) || []).length;
    expect(bodyTypeOccurrences).toBe(1);
  });
});

describe('generateServicesContent', () => {
  it('returns valid content for empty routes', () => {
    const content = generateServicesContent([], API_BASE, true);
    expect(content).toContain('Auto-generated by Vitek');
    expect(content).toContain("api.types");
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(0);
  });

  it('uses extensionless import for api.types (for Vite resolution)', () => {
    const routes = [route('health', 'get')];
    const content = generateServicesContent(routes, API_BASE, true);
    expect(content).toContain("from './api.types'");
    expect(content).not.toContain("from './api.types.js'");
  });

  it('generates exactly one function per unique route', () => {
    const routes = [
      route('health', 'get'),
      route('users/:id', 'get', ['id']),
    ];
    const content = generateServicesContent(routes, API_BASE, true);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(2);
    expect(new Set(names).size).toBe(2);
  });

  it('deduplicates routes: duplicate routeKey produces single export', () => {
    const routes = [
      route('flows/:id/run', 'post', ['id']),
      route('flows/:id/run', 'post', ['id']),
    ];
    const content = generateServicesContent(routes, API_BASE, true);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(1);
    expect(countOccurrences(content, names[0])).toBe(1);
  });

  it('deduplicates routes: same endpoint three times produces one function', () => {
    const routes = [
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'get', ['id']),
    ];
    const content = generateServicesContent(routes, API_BASE, true);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(1);
    expect(countOccurrences(content, names[0])).toBe(1);
  });

  it('no duplicate export names: every exported function appears exactly once', () => {
    const routes = [
      route('flows/:id/run', 'post', ['id']),
      route('flows/:id/run', 'post', ['id']),
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'post', ['id']),
      route('flows/:id/versions', 'post', ['id']),
      route('agents', 'get'),
    ];
    const content = generateServicesContent(routes, API_BASE, true);
    const names = getExportedFunctionNames(content);
    names.forEach((name) => {
      expect(countOccurrences(content, name)).toBe(1);
    });
    expect(names).toHaveLength(4);
  });

  it('mixed unique and duplicate routes: correct unique count', () => {
    const routes = [
      route('health', 'get'),
      route('health', 'get'),
      route('users/:id', 'get', ['id']),
      route('posts', 'post', []),
      route('posts', 'post', []),
    ];
    const content = generateServicesContent(routes, API_BASE, true);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(3);
    expect(new Set(names).size).toBe(3);
  });

  it('generates correct function name for flow run (no duplicated path in name)', () => {
    const routes = [route('flows/:id/run', 'post', ['id'])];
    const content = generateServicesContent(routes, API_BASE, true);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(1);
    expect(names[0]).toBe('postFlowsIdRun');
    expect(names[0]).not.toMatch(/FlowsIdRunFlowsIdRun/);
  });

  it('JavaScript output: also deduplicates and has no duplicate exports', () => {
    const routes = [
      route('flows/:id/run', 'post', ['id']),
      route('flows/:id/run', 'post', ['id']),
    ];
    const content = generateServicesContent(routes, API_BASE, false);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(1);
    expect(countOccurrences(content, names[0])).toBe(1);
  });

  it('many distinct routes: one function each, no duplicates', () => {
    const routes = [
      route('agents', 'get'),
      route('agents', 'post'),
      route('agents/:id', 'get', ['id']),
      route('agents/:id', 'put', ['id']),
      route('flows/:id/run', 'post', ['id']),
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'post', ['id']),
    ];
    const content = generateServicesContent(routes, API_BASE, true);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(7);
    expect(new Set(names).size).toBe(7);
    names.forEach((name) => {
      expect(countOccurrences(content, name)).toBe(1);
    });
  });

  it('generated file has no duplicate export declarations (regression for multiple exports error)', () => {
    const routes = [
      route('flows/:id/run', 'post', ['id']),
      route('flows/:id/run', 'post', ['id']),
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'post', ['id']),
      route('flows/:id/versions', 'post', ['id']),
    ];
    const content = generateServicesContent(routes, API_BASE, true);
    const names = getExportedFunctionNames(content);
    const byName = names.reduce<Record<string, number>>((acc, n) => {
      acc[n] = (acc[n] ?? 0) + 1;
      return acc;
    }, {});
    Object.entries(byName).forEach(([name, count]) => {
      expect(count).toBe(1);
    });
  });

  it('regression: flows/id/versions GET and POST each appear once', () => {
    const routes = [
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'get', ['id']),
      route('flows/:id/versions', 'post', ['id']),
      route('flows/:id/versions', 'post', ['id']),
    ];
    const content = generateServicesContent(routes, API_BASE, true);
    const names = getExportedFunctionNames(content);
    expect(names).toHaveLength(2);
    const getCount = names.filter((n) => n.startsWith('get')).length;
    const postCount = names.filter((n) => n.startsWith('post')).length;
    expect(getCount).toBe(1);
    expect(postCount).toBe(1);
    expect(countOccurrences(content, names[0])).toBe(1);
    expect(countOccurrences(content, names[1])).toBe(1);
  });
});

describe('generateTypesContent + generateServicesContent consistency', () => {
  it('same duplicate input: types and services have matching unique count', () => {
    const routes = [
      route('users/:id', 'get', ['id']),
      route('users/:id', 'get', ['id']),
      route('posts', 'post', []),
    ];
    const typesContent = generateTypesContent(routes, API_BASE);
    const servicesContent = generateServicesContent(routes, API_BASE, true);
    const typeParamNames = getExportedParamInterfaceNames(typesContent);
    const serviceNames = getExportedFunctionNames(servicesContent);
    expect(typeParamNames.length).toBe(serviceNames.length);
    expect(typeParamNames.length).toBe(2);
  });
});
