// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

export type VitekParams = Record<string, string>;
export type VitekQuery = Record<string, string | string[]>;


export type PostsPostBody = {
  title: string;
  content: string;
  authorId: number;
  tags?: string[];
};

export interface HealthGetParams extends VitekParams {

}

export interface PostsGetParams extends VitekParams {

}

export interface PostsPostParams extends VitekParams {

}

export interface UsersIdGetParams extends VitekParams {
  id: string;
}

export type VitekRoute =
  | {
      pattern: 'health';
      method: 'get';
      params: HealthGetParams;
    }
  | {
      pattern: 'posts';
      method: 'get';
      params: PostsGetParams;
    }
  | {
      pattern: 'posts';
      method: 'post';
      params: PostsPostParams;
    }
  | {
      pattern: 'users/:id';
      method: 'get';
      params: UsersIdGetParams;
    };

export const API_BASE_PATH = '/api' as const;
