// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

import { API_BASE_PATH } from './api.types';
import type { UsersIdGetParams, PostsPostBody } from './api.types';

export async function getHealth(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/health`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getPosts(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/posts`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function postPosts(body: PostsPostBody, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/posts`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function getUsersId(params: UsersIdGetParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/users/${params.id}`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}
