// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

import { API_BASE_PATH } from './api.types';
import type { StockSkuGetParams, MovementsPostBody } from './api.types';

export async function getHealth(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/health`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function postMovements(body: MovementsPostBody, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/movements`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function getStockSku(params: StockSkuGetParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/stock/${params.sku}`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getStock(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/stock`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}
