// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your socket files

import { SOCKET_BASE_PATH } from './socket.types.js';

export function connectAlerts(): WebSocket {
  const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  const url = new URL(`${protocol}//${window.location.host}${SOCKET_BASE_PATH}/alerts`);
  return new WebSocket(url.toString());
}
