// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your socket files

import type { WebSocket } from 'ws';
import type { IncomingMessage } from 'http';

export const SOCKET_BASE_PATH = '/api/ws' as const;

export interface VitekSocketContext {
  socket: WebSocket;
  req: IncomingMessage;
  params: Record<string, string>;
  path: string;
}

export type VitekSocket = WebSocket;


export type VitekSocketRoute =
  | {
      pattern: 'alerts';
      params: Record<string, never>;
    };
