// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

import { API_BASE_PATH } from './api.types';
import type { TasksIdGetParams, TeamsIdTasksGetParams, TeamsIdGetParams, TasksPostBody, ActivityGetQuery } from './api.types';

export async function getActivity(query: ActivityGetQuery, options?: RequestInit): Promise<any> {
  const url = new URL(`${API_BASE_PATH}/activity`, window.location.origin);
  Object.entries(query).forEach(([key, value]) => {
    url.searchParams.append(key, String(value));
  });
  return fetch(url.pathname + url.search, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getAdminSummary(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/admin/summary`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getHealth(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/health`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getTasksId(params: TasksIdGetParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/tasks/${params.id}`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function postTasks(body: TasksPostBody, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/tasks`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    body: JSON.stringify(body),
    ...options,
  }).then(res => res.json());
}

export async function getTeamsIdTasks(params: TeamsIdTasksGetParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/teams/${params.id}/tasks`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getTeamsId(params: TeamsIdGetParams, options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/teams/${params.id}`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}

export async function getTeams(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/teams`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}
