// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

export type VitekParams = Record<string, string>;
export type VitekQuery = Record<string, string | string[]>;


export type TasksPostBody = {
  teamId: string;
  title: string;
  assignee?: string;
};

export type ActivityGetQuery = {
  limit?: number;
};

export interface ActivityGetParams extends VitekParams {

}

export interface AdminSummaryGetParams extends VitekParams {

}

export interface HealthGetParams extends VitekParams {

}

export interface TasksIdGetParams extends VitekParams {
  id: string;
}

export interface TasksPostParams extends VitekParams {

}

export interface TeamsIdTasksGetParams extends VitekParams {
  id: string;
}

export interface TeamsIdGetParams extends VitekParams {
  id: string;
}

export interface TeamsGetParams extends VitekParams {

}

export type VitekRoute =
  | {
      pattern: 'activity';
      method: 'get';
      params: ActivityGetParams;
    }
  | {
      pattern: 'admin/summary';
      method: 'get';
      params: AdminSummaryGetParams;
    }
  | {
      pattern: 'health';
      method: 'get';
      params: HealthGetParams;
    }
  | {
      pattern: 'tasks/:id';
      method: 'get';
      params: TasksIdGetParams;
    }
  | {
      pattern: 'tasks';
      method: 'post';
      params: TasksPostParams;
    }
  | {
      pattern: 'teams/:id/tasks';
      method: 'get';
      params: TeamsIdTasksGetParams;
    }
  | {
      pattern: 'teams/:id';
      method: 'get';
      params: TeamsIdGetParams;
    }
  | {
      pattern: 'teams';
      method: 'get';
      params: TeamsGetParams;
    };

export const API_BASE_PATH = '/api' as const;
